/*
 * Fabric Engine 1.12.0
 * HelloWorld EDK Sample
 *
 * Copyright 2010-2014 Fabric Software Inc. All rights reserved.
 */

#include "HelloWorld.h" // Automatically generated by kl2edk

using namespace Fabric::EDK;
IMPLEMENT_FABRIC_EDK_ENTRIES( HelloWorld )

FABRIC_EXT_EXPORT void GetHelloWorldString(
  KL::String::Result result
  )
{
  Fabric::EDK::log("Extension: Enter GetHelloWorldString");
  result = "Hello, world!";
  Fabric::EDK::log("Extension: Leave GetHelloWorldString");
}
